name: Auto-label on Any Issue

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels to any new issue or PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelsToAdd = ["gssoc"];
            if (context.issue.pull_request) {
              // It's a Pull Request
              await github.pulls.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                labels: labelsToAdd
              });
            } else {
              // It's an Issue
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labelsToAdd
              });
            }
